# ---------------------------------------------------------------------------
# Secret management.
#
# The database password is generated by `random_password` and is written ONLY
# into AWS Secrets Manager, encrypted with a customer-managed KMS key. ECS
# decrypts it at task start and injects the connection fields into the
# container environment. Nothing in the repository or in a .env file ever
# carries a credential.
#
# Trade-off, documented in docs/CHALLENGES.md: `random_password` means the value
# also exists inside the Terraform state file. State is protected by S3 + KMS +
# versioning + DynamoDB locking and `prevent_destroy`. To remove even that, set
# `manage_master_user_password = true` on the RDS instance and inject from
# `master_user_secret[0].secret_arn` instead — see the note at the bottom.
# ---------------------------------------------------------------------------

resource "aws_kms_key" "secrets" {
  description             = "Encrypts Secrets Manager secrets for ${local.name_prefix}"
  deletion_window_in_days = 30
  enable_key_rotation     = true

  tags = { Name = "${local.name_prefix}-secrets-key" }
}

resource "aws_kms_alias" "secrets" {
  name          = "alias/${local.name_prefix}-secrets"
  target_key_id = aws_kms_key.secrets.key_id
}

resource "random_password" "db" {
  length  = 32
  special = true

  # Keep the alphabet free of characters that break connection URIs, shell
  # quoting or JSON escaping. Still ~190 bits of entropy.
  override_special = "!#$%&*()-_=+?"
}

resource "aws_secretsmanager_secret" "db" {
  name        = "${local.name_prefix}/db"
  description = "PostgreSQL connection details for ${local.name_prefix}. Injected into the ECS task at start."
  kms_key_id  = aws_kms_key.secrets.arn

  tags = { Name = "${local.name_prefix}/db" }

  # Never allow `terraform destroy` to silently drop a live credential.
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    engine   = "postgres"
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
  })
}

# Automatic rotation is deliberately out of the 9-12h happy path:
# `aws_secretsmanager_secret_rotation` requires a rotation Lambda, which would be
# another service to deploy, secure and own. To switch it on later, deploy
# aws-samples/aws-secrets-manager-rotation-lambdas and add:
#
#   resource "aws_secretsmanager_secret_rotation" "db" {
#     secret_id           = aws_secretsmanager_secret.db.id
#     rotation_lambda_arn = aws_lambda_function.rotate.arn
#     rotation_rules { automatically_after_days = 30 }
#   }
